version: '3.8'
services:
  mongodb:
    image: mongo:4.4.2
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - image-store-network

volumes:
  mongodb_data_container:

networks:
  image-store-network:
