version: '3.8'
services:
  image-store:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 10003:8080
    depends_on:
      - mongodb
    networks:
      - image-store-network

  mongodb:
    image: mongo:4.4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - image-store-network

volumes:
  mongodb_data_container:

networks:
  image-store-network:
